### ISSUE TITLE
Bad function

### ISSUE THREAD

**Issue by marcfedorow** [SUAI-Smart-Space-Team/smart-edge-control-software#10]
https://github.com/SUAI-Smart-Space-Team/smart-edge-control-software/blob/447a624826c88f7638cb5932e3cb28cd646a0f6e/commands/WebCommands.cpp#L5-L11

C++ std::string [provides](http://www.cplusplus.com/reference/string/string/substr/) `substr` function. Just use it.
[Asymptotic complexity](https://en.wikipedia.org/wiki/Big_O_notation) of your function is O(n^2) while `substr`'s is generally linear in the length of the returned object (O(n)).

**Comment by pinknemo452** [comment]
fixed
