### ISSUE TITLE
Excess brackets

### ISSUE THREAD

**Issue by marcfedorow** [SUAI-Smart-Space-Team/smart-edge-control-software#11]
https://github.com/SUAI-Smart-Space-Team/smart-edge-control-software/blob/447a624826c88f7638cb5932e3cb28cd646a0f6e/commands/WebCommands.cpp#L14-L20

```cpp
if (!data) return 0;
data->append(ptr, size * nmemb); 
return size * nmemb;
```

**Comment by pinknemo452** [comment]
fixed
