### ISSUE TITLE
Duplicate code

### ISSUE THREAD

**Issue by marcfedorow** [SUAI-Smart-Space-Team/smart-edge-control-software#13]
https://github.com/SUAI-Smart-Space-Team/smart-edge-control-software/blob/447a624826c88f7638cb5932e3cb28cd646a0f6e/commands/WebCommands.cpp#L36-L61

https://refactoring.guru/smells/duplicate-code

Do you want to create ten new functions for ten new features?
The code itself is bad (see #9 #12) but its copying is even worse.

**Comment by pinknemo452** [comment]
fixed
