### ISSUE TITLE
No catch

### ISSUE THREAD

**Issue by marcfedorow** [SUAI-Smart-Space-Team/smart-edge-control-software#14]
https://github.com/SUAI-Smart-Space-Team/smart-edge-control-software/blob/447a624826c88f7638cb5932e3cb28cd646a0f6e/commands/WebCommands.cpp#L44

`stoi` throws `std::invalid_argument` and `std::out_of_range` but you don't catch it. Also you don't even check the `fan` value.
Will it spin in the opposite direction if I set it to -50?
Because of #13 you should re-write all the places containing this code.

**Comment by pinknemo452** [comment]
fixed
