### ISSUE TITLE
get != print

### ISSUE THREAD

**Issue by marcfedorow** [SUAI-Smart-Space-Team/smart-edge-control-software#15]
https://github.com/SUAI-Smart-Space-Team/smart-edge-control-software/blob/447a624826c88f7638cb5932e3cb28cd646a0f6e/commands/WebCommands.cpp#L36
https://github.com/SUAI-Smart-Space-Team/smart-edge-control-software/blob/447a624826c88f7638cb5932e3cb28cd646a0f6e/commands/WebCommands.cpp#L43

The function name does not imply that anything will be printed.

**Comment by pinknemo452** [comment]
fixed
