### ISSUE TITLE
CPU stress test?

### ISSUE THREAD

**Issue by ghost** [SUAI-Smart-Space-Team/smart-edge-control-software#16]
Are you sure it's a good idea to run something in an infinite loop? In my opinion, this is more like a DOS attack on the web server or a good attempt to kill the processor, especially if you do it in several threads. In my opinion, it would be better to use callback functions with a delay.

https://github.com/SUAI-Smart-Space-Team/smart-edge-control-software/blob/c4f8e560f6c092e9a775e61b71bbe841939c1e9c/main.cpp#L9-L12

**Comment by pinknemo452** [comment]
fixed
