### ISSUE TITLE
Function override

### ISSUE THREAD

**Issue by ghost** [SUAI-Smart-Space-Team/smart-edge-control-software#17]
Using the *override* or (rarely) *final* modifier does not affect the efficiency or performance of the program in any way, but it helps to avoid unintended errors. Hence, it is highly recommended that you use the *override* modifier for each of your overrides.

https://github.com/SUAI-Smart-Space-Team/smart-edge-control-software/blob/c4f8e560f6c092e9a775e61b71bbe841939c1e9c/devices/Device.h#L6-L7

**Comment by pinknemo452** [comment]
fixed
