### ISSUE TITLE
Error messaging

### ISSUE THREAD

**Issue by marcfedorow** [SUAI-Smart-Space-Team/smart-edge-control-software#4]
https://github.com/SUAI-Smart-Space-Team/smart-edge-control-software/blob/447a624826c88f7638cb5932e3cb28cd646a0f6e/devices/Device.cpp#L18-L19

It seems to be an C++ project so it's reasonable to use either
```cpp
std::cerr << string("error message") << std::endl;
```
or
```cpp
throw some_custom_exception("exception description");
```

**Comment by pinknemo452** [comment]
fixed
