### ISSUE TITLE
std::string_view

### ISSUE THREAD

**Issue by ghost** [SUAI-Smart-Space-Team/smart-edge-control-software#47]
https://github.com/SUAI-Smart-Space-Team/smart-edge-control-software/blob/dfd262392700cc49c70c77f9692d7542b147d875/main.cpp#L7

**Comment by marcfedorow** [comment]
I think that const string is good enough

**Comment by ghost** [comment]
> I think that const string is good enough

This string is much longer than 16 characters, so "small string optimization" cannot be used. Accordingly, the new operator will be called again and the memory will be allocated. Perhaps constexpr can optimize this, but it's easier to use string_view
