### ISSUE TITLE
UB?

### ISSUE THREAD

**Issue by marcfedorow** [SUAI-Smart-Space-Team/smart-edge-control-software#7]
https://github.com/SUAI-Smart-Space-Team/smart-edge-control-software/blob/447a624826c88f7638cb5932e3cb28cd646a0f6e/devices/Device.cpp#L66
What do you want to copy from `rgbstring.size() + 1`? 
[cppreference](http://www.cplusplus.com/reference/string/string/c_str/) says:
_This array includes the same sequence of characters that make up the value of the string object plus an additional terminating null-character ('\0') at the end._

**Comment by pinknemo452** [comment]
fixed
