### ISSUE TITLE
char* vs std::string

### ISSUE THREAD

**Issue by marcfedorow** [SUAI-Smart-Space-Team/smart-edge-control-software#8]
https://github.com/SUAI-Smart-Space-Team/smart-edge-control-software/blob/447a624826c88f7638cb5932e3cb28cd646a0f6e/commands/WebCommand.h#L11-L12
I do not understand why you use both `std::string` and raw `char*`.
Either set a comment (e.g. "`_html `is rarely used but `link` participates in frequently used operations") or change it.

**Comment by pinknemo452** [comment]
fixed
